### ISSUE TITLE
Subsurface scattering controls are not operational

### ISSUE THREAD

**Issue by iaian7** [GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon#307]
## Issue

The subsurface settings in the RPR Uber node do not work when rendering in "full" quality mode.

#### Blender 2.93.1 with the Radeon ProRender 3.1.25 plugin

Radius and direction settings are both non-responsive, and it seems that the subsurface feature is locked to a look that roughly matches diffuse backscattering set to 1.0.

![Subsurface-293-3125](https://user-images.githubusercontent.com/142759/124205227-d05f4000-daae-11eb-8733-dcc5b1b2346a.jpg)

#### Blender 2.93.1 with the Radeon ProRender 3.1.16 plugin

Direction setting is non-responsive, but radius appears to be working.

![Subsurface-293-3116](https://user-images.githubusercontent.com/142759/124205162-a9087300-daae-11eb-9603-167336bd8c36.jpg)

#### Blender 2.83.16 with the Radeon ProRender 2.5.1 plugin

I've confirmed the two newer versions of the plugin listed above, when set to "Legacy" render quality, matches the older plugin rendered output (the RPR Uber node issue doesn't appear to affect legacy mode).

![Subsurface-283-251](https://user-images.githubusercontent.com/142759/124204952-2b446780-daae-11eb-8ff7-8048b4cf5a03.jpg)

#### Blender 2.93.1 with Cycles

Of particular note, regarding the Radeon ProRender engine in general not the Blender plugin I presume, is that the subsurface settings in Cycles are significantly more usable from an artist perspective. Every single example posted here uses the same hue, saturation, and brightness as inputs, but Radeon ProRender introduces _significant_ shifts in colour and luminosity. I imagine the RPR method is technically more accurate (calculating sub-surface bounces as recursively filtered, and allowing subsurface to absorb instead of bounce diffuse lighting, darkening things significantly), but it makes it a _lot_ more difficult to use in a motion graphics situation (and more photoreal situations too, unfortunately).

I will say the backscattering (translucency) setup in Cycles is a little silly; I much prefer the RPR Uber shader system in that regard!

![Subsurface-293-Cycles](https://user-images.githubusercontent.com/142759/124205074-7cecf200-daae-11eb-9cc7-0238f1574689.jpg)

## Steps to Reproduce
- Create objects and materials
- Set up the RPR Uber shader with subsurface scattering enabled
- Render
- Change any of the subsurface settings
- Render again (nothing changes)

### Scene files

- Subsurface-283-RPR.blend
- Subsurface-293-Cycles.blend
- Subsurface-293-RPR.blend

[BlenderFiles.zip](https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon/files/6751429/BlenderFiles.zip)

## System Setup (Environment)
macOS Big Sur version 11.4
2.4 GHz 8-Core Intel Core i9
64 GB DDR4 RAM
AMD Radeon Pro 5600M 8 GB
Razer Core X eGPU with AMD Radeon RX 5700 XT
Blender 2.83.16 and Blender 2.93.1
Using mostly default settings in RPR (render quality set to full in the 3.x plugins)
Rendering on the eGPU

## Detailed Description
The primary concern is that the RPR Uber node settings simply do not work in the latest build. Previous versions (3.1.16 specifically) were only partially operational, so it seems this is an actively devolving issue.

**Comment by iaian7** [comment]
No change in 3.2.2; it renders identically to 3.1.25. Radius and Direction settings are inoperable.

**Comment by ARozghon** [comment]
Hi, @iaian7, thank you for your request. For now, SSS Radius has the most visual effect with values from 0 to 1, like on screenshot 1
![image](https://user-images.githubusercontent.com/68949117/124783887-148a8e80-df4e-11eb-926c-b9cc11c0b907.png)
also, if set values for SSS like on screenshot2 ![image](https://user-images.githubusercontent.com/68949117/124784141-51ef1c00-df4e-11eb-8105-e8a7ba3a9534.png) RPR will show good results too
in RPR 3.2.2 used the same core as RPR 3.1.25 have, that's why you get the equal results and one of the future core will improve volumes and SSS quality
Thank you

**Comment by iaian7** [comment]
The example I originally posted demonstrated settings of 0.1 and 1.0, the range you describe as being most effective, but there is no visual difference between them. I've tried 0.01 and 0.001 settings as well, and there is no visual change. Sub-surface scattering renders identically, regardless of settings, to the diffuse backscatter setting.

**Comment by iaian7** [comment]
Render from Blender 2.93.1 with Radeon ProRender for Blender 3.2.2. No matter what settings are used, subsurface output never changes, and is identical to backscatter.

![Subsurface-293-322](https://user-images.githubusercontent.com/142759/125092038-ea94b180-e09e-11eb-9a56-6d9dd33c811b.jpg)

[Subsurface-293-322.blend.zip](https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon/files/6792031/Subsurface-293-322.blend.zip)

**Comment by bsavery** [comment]
possibly fixed with #309

**Comment by ARozghon** [comment]
![image](https://user-images.githubusercontent.com/68949117/127318772-652fe235-cc0a-4d87-a928-7f5f5091663d.png)
results with implemented #309

**Comment by ARozghon** [comment]
@iaian7, please, check your issue with the latest build with implemented #309 and more https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon/releases/tag/v3.2.12

**Comment by iaian7** [comment]
Interesting results:

- CPU based rendering now reflects the Subsurface Radius setting, but Subsurface Direction still doesn't have any affect.
- GPU rendering (the entire reason to use RPR) is still entirely broken (regardless of settings, subsurface is rendered as backscattering).
- Rendering with CPU and GPU systems simultaneously actually renders (last time I tried this, it just resulted in garbled pixels!), but has the same issues as GPU-alone rendering; subsurface scattering controls are ignored.

![Subsurface-293-3212-CPU](https://user-images.githubusercontent.com/142759/127512740-6c6d234b-4605-457b-82b6-aed7d08ae098.jpg)

![Subsurface-293-3212-GPU](https://user-images.githubusercontent.com/142759/127512760-b47d6c6a-6148-4e6f-bfe3-0332cf3c1355.jpg)

![Subsurface-293-3212-eGPU](https://user-images.githubusercontent.com/142759/127512766-6aba0148-eab1-4919-942f-352435c61eb5.jpg)

![Subsurface-293-3212-CPU-eGPU-GPU](https://user-images.githubusercontent.com/142759/127512774-80831eb7-154f-4d62-a3d8-7204185cd6d1.jpg)

**Comment by ARozghon** [comment]
Hi, as I know, new features for SSS have not been implemented for macOS, now SSS Radius and Volumes are supported on Windows and Ubuntu
