### ISSUE TITLE
Blender 4.0

### ISSUE THREAD

**Issue by Brasennus** [GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon#665]
Fairly straight forward, pro render doesn’t install / is not compatible with blender 4. Tried both Linux and windows. Is this something that will be updated in the near future? (Planning ahead to account for a project). 

Thanks kindly.

**Comment by bsavery** [comment]
Checkout this pull request https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon/pull/660

**Comment by juanjoseluisgarcia** [comment]
The fact that is the community supporting this and the fact that a PR is not yet approved with Blender 4.0 more than a month out is the reason I am glad that I moved to a M3 Max. For PC I'd go with NVidia. This is by any standard not a serious graphics card.

**Comment by bsavery** [comment]
> The fact that is the community supporting this and the fact that a PR is not yet approved with Blender 4.0 more than a month out is the reason I am glad that I moved to a M3 Max. For PC I'd go with NVidia. This is by any standard not a serious graphics card.

Hi Juan.  I'm genuinely confused by your comment for a few reasons.
1.  This is a repository for a free addon to Blender.  Software, not a graphics card.  So can you clarify what you mean by "This is by any standard not a serious graphics card."?  You are correct, this is not a graphics card.
2.  The PR has in fact been approved, just not merged.  I just merged it.
3.  The PR was done by AMD people, not the community.  We would love community contributions too!  This is why we made it open source.  Do you want to contribute? 
4.  Actually you mention Mac and NVidia.  We actually support those as well as AMD cards.  
5.  Furthermore it is true there has been less activity here.  We have been focusing on other things now there is native AMD support with HIP in cycles and the USD Hydra contributions we made to the Blender codebase.
6.  It took a bit longer to merge things because of holidays.

If you want to contribute we'd welcome it!  If you're just here to throw shade, surely there are better places than in the comments of github issues.

**Comment by juanjoseluisgarcia** [comment]
Apologies @bsavery I thought this was an official plugin plus the fact that I was shock I many orders of magnitude I got to render from my M3 Max to my old Radeon Pro 5600M (I stopped at 5:30 minutes without seeing a single pixel while the max finishes at 40s) and I saw this plugin to try to see if things improved.

**Comment by microBob** [comment]
> The PR has in fact been approved, just not merged. I just merged it.

🥳 

Where can we find a general timeline for official releases? I see that this has been merged into master, but I'm a bit tentative on using the plugin directly from master. Thanks!

**Comment by ApurvZ** [comment]
@bsavery There's also not many activity on other ProRender forum for Maya. Last updated on May 26th 2023. And still not support for Maya 2024. There's no Arnold support for AMD cards. Talked with maya users in a discord group having Radeon GPUs, they don't have a nice opinion about ProRender for Maya. Radeon users there are using CPU rendering instead of GPU.

I guess @juanjoseluisgarcia meant that, radeon is probably not a good choice for 3D artists working in the 3D industry as a whole. As 3D industry softwares like Maya, 3DS Max, and even from other branch of science, like MATLAB a mathematical modeling software doesn't recognises Radeon GPUs. Even a recent [ZLUDA](https://github.com/vosen/ZLUDA) implementation has increased [blender benchmark](https://opendata.blender.org/benchmarks/query/?compute_type=OPTIX&compute_type=CUDA&compute_type=HIP&compute_type=METAL&compute_type=ONEAPI&group_by=device_name&blender_version=4.0.0) rankings of AMD GPUs. I guess AMD needs to work hard in this areas, to better present their products, not just in gaming performances.

**Comment by Brasennus** [comment]
> @bsavery There's also not many activity on other ProRender forum for [Maya](https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRenderMayaPlugin/releases/tag/v3.5.0). Last updated on May 26th 2023. And still no support for Maya 2024. There's no Arnold support for AMD cards. Talked with maya users in a discord group having Radeon GPUs, they don't have a nice opinion about ProRender for Maya. Radeon users there are using CPU rendering instead of GPU.
> 
> I guess @juanjoseluisgarcia meant that, radeon is probably not a good choice for 3D artists working in the 3D industry as a whole. As 3D industry softwares like Maya, 3DS Max, and even from other branch of science, like MATLAB a mathematical modeling software doesn't recognises Radeon GPUs. Even a recent [ZLUDA](https://github.com/vosen/ZLUDA) implementation has increased [blender benchmark](https://opendata.blender.org/benchmarks/query/?compute_type=OPTIX&compute_type=CUDA&compute_type=HIP&compute_type=METAL&compute_type=ONEAPI&group_by=device_name&blender_version=4.0.0) rankings of AMD GPUs. I guess AMD needs to work hard in this areas, to better present their products, not just in gaming performances.

This isn’t the forum for what you are wanting to discuss. At what point are any of your opinions relevant to the original question?

**Comment by takahiroharada** [comment]
FYI @Brasennus  https://github.com/GPUOpen-LibrariesAndSDKs/RadeonProRenderBlenderAddon/releases/tag/v3.6.10
